name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
  workflow_call:
    secrets:
      METRICS_TOKEN:
        required: true
jobs:
  metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Metrics
        uses: lowlighter/metrics@master
        with:
          plugin_lines: yes
          filename: metrics.classic.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          config_timezone: America/New_York
      - name: languages
        uses: lowlighter/metrics@latest
        with:
          plugin_languages: yes
          filename: metrics.plugin.languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages_limit: 10
